### ISSUE TITLE
any way to get/set users per rooms

### ISSUE THREAD

**Issue by camous** [germanrcuriel/hipchat-client#13]
I'm not able to find how getting/settings users to room. did I miss something such some hidden functionality (I've looked into repository without success).

**Comment by germanrcuriel** [comment]
Hi @camous. I guess you should probably look for an API v2 client instead. API v1 is deprecated and doesn't have as many limitations as v1.

Of course, you can get users in a room, but you can't set the users to one.

In room details response you can get the users on it:
https://github.com/germanrcuriel/hipchat-client/blob/master/docs/rooms.md#get-room-details

Regards

**Comment by camous** [comment]
Thanks for the information. I've looked afterward to a nodejs wrapper for v2 (https://github.com/charltoons/hipchatter) but initially I miss read the last modified date: read 3 years rather 3 days :) but still same situation, I see no way to add users to a room.

**Comment by germanrcuriel** [comment]
@camous Well, they do have support for that.

https://github.com/charltoons/hipchatter/blob/master/hipchatter.js#L57

**Comment by camous** [comment]
@germanrcuriel indeed, i was too much focusing on the documentation and not the source code. thanks for pointing it out.
