### ISSUE TITLE
TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by jwngr** [germanrcuriel/hipchat-client#8]
We have a backend server which sends HipChat notifications using this v1.0.3 of this module a few times a day and we recently hit an error with the following stack trace:

```
Stack Trace: TypeError: Cannot read property 'code' of undefined
   at Rooms.BaseClass.throwError (/Production/admin-backend/node_modules/hipchat-client/lib/api/common/base_class.js:15:34)
   at /Production/admin-backend/node_modules/hipchat-client/lib/api/common/base_class.js:45:35
   at Request.callback (/Production/admin-backend/node_modules/hipchat-client/node_modules/superagent/lib/node/index.js:729:30)
   at Request. (/Production/admin-backend/node_modules/hipchat-client/node_modules/superagent/lib/node/index.js:135:10)
   at Request.emit (events.js:95:17)
   at ClientRequest. (/Production/admin-backend/node_modules/hipchat-client/node_modules/superagent/lib/node/index.js:890:12)
   at ClientRequest.emit (events.js:95:17)
   at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
   at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
   at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
```

It appears that [the `error` object being passed to `throwError()`](https://github.com/germanrcuriel/hipchat-client/blob/7ac03fa6ac160d6ba848fc55b83177ad602d2d79/src/api/common/base_class.coffee#L9) is `undefined`. I know this isn't a ton of information and I have no reliable repro, but I just wanted to make you aware of it and see if you had any ideas for what went wrong.

We recently upgraded to version 1.0.3 and had never hit this issue before then, so it's possible this is a recent regression. Let me know if I can get you any more useful information.

**Comment by jwngr** [comment]
The request we make looks like this:

```
hipchat.api.rooms.message({
  room_id: <roomId>,
  from: 'Firebase',
  message: <message>,
  notify: 1,
  color: 'green',
  message_format: 'text'
}, function(error, response) {
  // ...
});
```

**Comment by germanrcuriel** [comment]
Hi @jwngr,

First of all, thanks for notifying!

Does it happen always? I was testing it for a while and I can't reproduce it.

My guess is that the error could be produced by an unexpected response from HipChat API. When an API request doesn't return a `2XX` response code it prepares an Error object, using the response itself. An example of error response from HipChat API looks like following:

```json
{
  "error": {
    "code": 401,
    "type": "Unauthorized",
    "message": "Auth token invalid. Please see: https:\/\/www.hipchat.com\/docs\/api\/auth"
  }
}
```

It seems like `error` node is missing when error happens.

The only difference between 1.0.2 and 1.0.3 is a dependency moved from `dependencies` to `devDependencies` in `package.json`.

**Comment by jwngr** [comment]
It has only happened this one time, which is why I think it's going to be hard to track down (and why I'm not surprised you weren't able to repro it). I noticed that the `1.0.3.` upgrade was functionally the same as `1.0.2` after I posted my message, so that isn't it.

I certainly would not be surprised if the HipChat API just returned a bad error response for a short period of time. So it may have just been an ephemeral issue. The only real "fix" I can think of would be to do validation on the `error` object passed into `throwError()`. I'm not sure if that's something you are interested in doing though.

**Comment by germanrcuriel** [comment]
Yes, I think I would check the object before passing to `throwError()` and set a default one just in case.

**Comment by jwngr** [comment]
Sweet, thanks!

**Comment by Hu13er** [comment]
.

**Comment by Hu13er** [comment]
dfdfd

**Comment by germanrcuriel** [comment]
@Hu13er WTF?
